### ISSUE TITLE
Translation: English to 10 languages for FAQs | CSVs - upload and verify

### ISSUE THREAD

**Issue by rishabhbeehyv** [Kumbh-SahAIyak/.github#11]

**Comment by rishabhbeehyv** [comment]
@ranju97 , Please provide sample csv for the translation

**Comment by ranju97** [comment]
Attaching a workbook which is a Knowledge Graph for the "About Kumbh" use case. [**Link**](https://docs.google.com/spreadsheets/d/1r1Nn8sR3HGsRMmyNAH3oAFjuEsSdQWxZIN_mTib7C0Q/edit?usp=sharing)

The workbook has 3 sheets:

**1. Sheet Name: About Kumbh | Graph Layout**
This sheet lays out a graph of nodes for the use case with a mapping to template answers. 
**2. Sheet Name: Template Answers**
This sheet has the actual template answers written along with answer numbers which would help map to the previous sheet. Some answers have <prefix> & <suffix> tags present which are yet to be finalized.
**3. Sheet Name: FAQs Sheet**
This sheet has a list of FAQ questions for every node in the graph. Please note that we are yet to populate answers for these questions.

**Example Flow:**
If a user clicks on About Kumbh, the template answer mapped with name "Use Case Message" will be picked & displayed to the user along with other child nodes of the About Kumbh node which are "History", "Significance", "Rituals", etc. If the user then clicks on "Significance", Answer 5 will have to be picked from the "Template Answers" sheet.

**Translation Requirement:**
We want the 3 sheets to be reproduced as is in 10 different languages, with the following columns in each of the sheets translated:

1. Sheet Name: About Kumbh | Graph Layout
Column - C (Node 1), E (Node 2), G (Node 3), I (Node 4)
2. Sheet Name: Template Answers
Column - C (Template Response)
3. Sheet Name: FAQs Sheet
The entire sheet should be translated. All columns from B to G.

**Comment by rishabhbeehyv** [comment]
@ranju97 , Can you share access for the sheet unable to access?

**Comment by sitanshu-pugalia** [comment]
@vikasbeehyv Translation content and script has been shared. Let us know if anything else is needed.

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia , I haven't received any scripts for translation yet, could you please confirm where have they been shared.

**Comment by sitanshu-pugalia** [comment]
@vikasbeehyv Amruthi has shared it in the discord channel. Thread link: https://discord.com/channels/959457910604333107/1277903915475796011/threads/1280034611057000501

**Comment by sitanshu-pugalia** [comment]
@vikasbeehyv  Can you please confirm by when can you share the translated output today ? Accordingly, we can align the team for validating the output.
CC: @baggasimran

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia, around 5-6PM.

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia, PFA sample translation csv file. 

[Translations.csv](https://github.com/user-attachments/files/16838018/Translations.csv)

**Comment by sitanshu-pugalia** [comment]
@vikasbeehyv There are two more sheets in the doc shared by Ranju that needs to be translated. Can you please share the output for the other two sheets as well by 1st half ?

**Comment by ranju97** [comment]
@vikasbeehyv The first comment on this ticket mentions the exact columns in the 3 sheets that needs to be translated. Can we have the script updated for the same. Also, can we see the output post this update?

Bringing up the translation requirements.

**Translation Requirement:**
We want the 3 sheets to be reproduced as is in 10 different languages, with the following columns in each of the sheets translated:

Sheet Name: About Kumbh | Graph Layout
Column - C (Node 1), E (Node 2), G (Node 3), I (Node 4)
Sheet Name: Template Answers
Column - C (Template Response)
Sheet Name: FAQs Sheet
The entire sheet should be translated. All columns from B to G.

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia @ranju97 . PFA translationScript zip which contains scripts as well as readme.md file.

[Translation Script v1.zip](https://github.com/user-attachments/files/16846340/Translation.Script.v1.zip)

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia @ranju97 . After reviewing the provided translation script, please let me know if you have any additional requirements or adjustments needed.

**Comment by sitanshu-pugalia** [comment]
Translation Input Sheet (Format): https://docs.google.com/spreadsheets/d/13qeDsR58pjIb13kSJZzKe6Xtj8yu7Nv3hdsZkGU_Tg0/edit?gid=1073217455#gid=1073217455

**Comment by vikasbeehyv** [comment]
> Translation Input Sheet (Format): https://docs.google.com/spreadsheets/d/13qeDsR58pjIb13kSJZzKe6Xtj8yu7Nv3hdsZkGU_Tg0/edit?gid=1073217455#gid=1073217455

@sitanshu-pugalia , please provide access for this sheet.

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia, have a look at these two for the nodes and the template response, do they work as per your requirements. 

[template_response_output.csv](https://github.com/user-attachments/files/16868572/template_response_output.csv)
[template_response_input.csv](https://github.com/user-attachments/files/16868575/template_response_input.csv)
[nodes_output.csv](https://github.com/user-attachments/files/16868574/nodes_output.csv)
[nodes_input.csv](https://github.com/user-attachments/files/16868573/nodes_input.csv)

**Comment by ranju97** [comment]
@vikasbeehyv This looks good. Additionally we'd also require the FAQ sheet to be translated in the 10 languages including Urdu

Translation Input Sheet (Format): https://docs.google.com/spreadsheets/d/13qeDsR58pjIb13kSJZzKe6Xtj8yu7Nv3hdsZkGU_Tg0/edit?gid=1073217455#gid=1073217455

**Comment by vikasbeehyv** [comment]
@ranju97  @sitanshu-pugalia. PFA attached zip for the translation works. Here are four separate csvs. Two for nodes and template response and among the rest two, one contains the faq and the other faq answer. Also with sheet sample code is added in the first column of sheet.

[TranslationScriptV1.zip](https://github.com/user-attachments/files/16884116/TranslationScriptV1.zip)

**Comment by sitanshu-pugalia** [comment]
@vikasbeehyv As discussed, kindly share a csv with 3 sheets: nodes, answers, FAQ questions and answers

**Comment by vikasbeehyv** [comment]
@sitanshu-pugalia, PFA attached combined csvs excel, consisting of all the 3 sheets with the translations.

[combined_csvs.xlsx](https://github.com/user-attachments/files/16895710/combined_csvs.xlsx)
