### ISSUE TITLE
Testing by tweaking existing models

### ISSUE THREAD

**Issue by saibeehyv** [Kumbh-SahAIyak/.github#74]

**Comment by himanshu-beehyv** [comment]
It is a blocker. Plateform has issues. Missing logs for debugging - flowise bugs(no option while asking query)![Image](https://github.com/user-attachments/assets/da53add8-340b-49a5-bb9c-a9306022d971)
Also python scripts works which means Llama works like Operai earlier. Possibly bug exists in chat bot at plateform level
